version: '3'
services:
  vuejs:
    image: your_vuejs_image
    ports:
      - '8080:8080'
    depends_on:
      - springboot

  patient-service:
    image: microservice-patient:0.0.1
    ports:
      - '9000:9000'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/microservicepatient
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootroot
    depends_on:
      - mysql

  mysql:
    image: your_mysql_image
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=microservicepatient
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootroot
      - MYSQL_ROOT_PASSWORD=rootpassword