version: '3'
services:
  vuejs:
    image: medilabo-front:latest
    ports:
      - '8080:8080'
    restart: on-failure

  note-service:
    image: medilabo-notes:latest
    ports:
      - '9001:9001'
    environment:
      - MONGO_URL=mongodb://mongodb:27017/patients-notes
    depends_on:
      - mongodb

  report-service:
    image: medilabo-rapport:latest
    ports:
      - '9002:9002'
    restart: on-failure

  patient-service:
    image: medilabo-patient
    ports:
      - '9000:9000'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/microservicepatient?serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=mypassword
    depends_on:
      - mysql
    restart: on-failure

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    restart: on-failure

  mysql:
    image: mysql:latest
    ports:
       - '3307:3306'
    environment:
      - MYSQL_DATABASE=microservicepatient
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
          - ./data_patients.sql:/docker-entrypoint-initdb.d/data_patients.sql
    restart: on-failure
    
  gateway:
    image: medilabo-gateway:latest
    ports:
      - '8000:8000'
    depends_on:
      - vuejs
      - note-service
      - report-service
      - patient-service

