server:
  port: 8000

spring:
  cloud:
    gateway:
      routes:
        - id: vuejs-frontend
          uri: http://vuejs:8080/
          predicates:
            - Path=/ui/**
          filters:
            - StripPrefix=1

        - id: patient
          uri: http://patient-service:9000
          # uri: http://localhost:9000/
          predicates:
            - Path=/patients/**

        - id: note
          #          uri: http://note-service:9001/
          uri: http://localhost:9001/
          predicates:
            - Path=/notes/**

        - id: report
          uri: http://report-service:9002
          # uri: http://localhost:9002/
          predicates:
            - Path=/report/**
